#!/usr/bin/env bash
[[ $1 == "" ]] && echo "u have to input a file!!" && exit

sed -e 's|^|<p class="text" >|' $1 > thingies/$1.tmp

sed -ie 's|^<p class="text" >title: |<p class="text title" >|' thingies/$1.tmp
sed -ie 's|^<p class="text" >subtitle: |<p class="text subtitle" >|' thingies/$1.tmp
sed -ie 's|^<p class="text" >image: |<img class="center" src="/images/|' thingies/$1.tmp
sed -ie 's|^<p class="text" >song: |<audio id="music" autoplay><source src="|' thingies/$1.tmp

sed -ie '/^<p class="text" >/ s|$|</p>|' thingies/$1.tmp

sed -ie '/^<p class="text title" >/ s|$|</p>|' thingies/$1.tmp
sed -ie '/^<p class="text subtitle" >/ s|$|</p>|' thingies/$1.tmp
sed -ie '/^<img class="center" src="\/images\// s|$|">|' thingies/$1.tmp
sed -ie '/^<audio id="music" autoplay><source src="/ s|$|" type="audio/mpeg"></audio>|' thingies/$1.tmp

sed -ie 's|^|\t|' thingies/$1.tmp

cat thingies/top.html > $1.html
cat thingies/$1.tmp >> $1.html
cat thingies/bottom.html >> $1.html

rm thingies/$1.tmp
