#!/usr/bin/env bash

DATE=$(date +%d.%m.%y)

[[ $1 == "" ]] && echo "u have to input a file!!" && exit

cat thingies/top.html > html/blog.html

sed -e 's|^title: ||' $1 > thingies/blog_middle.tmp0

sed -n '1p' thingies/blog_middle.tmp0 > thingies/blog_middle.tmp1
sed -ie "/^/ s/\$/ (${DATE})/" thingies/blog_middle.tmp1

sed -e "s|^|<a href='' class='text' >|" thingies/blog_middle.tmp1 > thingies/blog_middle.tmp2
sed -ie "s|^<a href=''|<a href='/html/blogs/${1}.html'|" thingies/blog_middle.tmp2
sed -ie 's|$|</a>|' thingies/blog_middle.tmp2
echo "<p></p>" >> thingies/blog_middle.tmp2
sed -ie 's|^|\t|' thingies/blog_middle.tmp2

cat thingies/blog_middle.tmp2 >> thingies/blog_middle.html
cat thingies/blog_middle.html >> html/blog.html
cat thingies/bottom.html >> html/blog.html

sed -e 's|^|<p class="text" >|' $1 > thingies/$1.tmp

sed -ie 's|^<p class="text" >title: |<p class="text title" >|' thingies/$1.tmp
sed -ie 's|^<p class="text" >subtitle: |<p class="text subtitle" >|' thingies/$1.tmp
sed -ie 's|^<p class="text" >image: |<img class="center" src="/images/|' thingies/$1.tmp
sed -ie 's|^<p class="text" >song: |<audio id="music" autoplay><source src="|' thingies/$1.tmp
sed -i 's|^<p class="text" >link: (|<a class="text" href="|' thingies/$1.tmp

sed -ie '/^<p class="text" >/ s|$|</p>|' thingies/$1.tmp
sed -ie '/^<p class="text title" >/ s|$|</p>|' thingies/$1.tmp
sed -ie '/^<p class="text subtitle" >/ s|$|</p>|' thingies/$1.tmp
sed -ie '/^<img class="center" src="\/images\// s|$|">|' thingies/$1.tmp
sed -ie '/^<audio id="music" autoplay><source src="/ s|$|" type="audio/mpeg"></audio>|' thingies/$1.tmp
sed -i '/^<a class="text" href="/ s|) |">|' thingies/$1.tmp
sed -i '/^<a class="text" href="/ s|$|</a>|' thingies/$1.tmp

sed -ie 's|^|\t|' thingies/$1.tmp

cat thingies/top.html > blogs/$1.html
cat thingies/$1.tmp >> blogs/$1.html
cat thingies/bottom.html >> blogs/$1.html

rm thingies/*.tmp*
